// Built-in module registry (OWNER: K0). Lanes do not edit this file: each lane only fills its own folder.
// Third-party plugins are passed to createLiveforge({ modules: [...BUILTIN_MODULES, myPlugin] }).
import type { LiveforgeModule } from "../module.js";
import observer from "./observer/index.js";
import persona from "./persona/index.js";
import world from "./world/index.js";
import director from "./director/index.js";
import forge from "./forge/index.js";
import quests from "./quests/index.js";
import factions from "./factions/index.js";

import agents from "./agents/index.js";
import builder from "./builder/index.js";

export const BUILTIN_MODULES: LiveforgeModule[] = [observer, persona, world, director, forge, quests, agents, builder, factions];

/** Which built-in module answers each ask kind (documentation + sanity check at startup). */
export const ASK_OWNERS: Record<string, string> = {
  "npc.bark": "persona", "npc.reply": "persona",
  "director.boss_phase": "director", "director.boss_move": "director", "director.encounter": "director", "director.pacing": "director",
  "forge.item": "forge", "forge.armour_set": "forge", "forge.look": "forge", "forge.vfx": "forge", "forge.creature": "forge",
  "forge.npc_look": "forge", "forge.prop": "forge", "forge.loot": "forge", "forge.thing": "forge",
  "quest.offer": "quests", "achievement.check": "quests",
  "world.reactions": "world",
  "player.model": "observer",
  "faction.raid_plan": "factions",
  "builder.plan": "builder",
  "agent.goal": "agents",
};
